export const SAVE_LIMIT = 60;
export const CONTEXT_LIMIT = 20;
export const BIDIRECTIONAL_LIMIT = 20;
export const BIDIRECTIONAL_KEY = 'PHONE_SMS_MEMORY';
export const MAX_INJECTION_CHARS = 24000;
export const CALENDAR_STORAGE_KEY = 'ST_SMS_CALENDAR_V1';
export const CALENDAR_OCCASION_STORAGE_KEY = 'ST_SMS_CALENDAR_OCCASIONS_V1';
export const CALENDAR_HOLIDAY_STORAGE_KEY = 'ST_SMS_CALENDAR_HOLIDAYS_V1';
export const CALENDAR_WEATHER_STORAGE_KEY = 'ST_SMS_CALENDAR_WEATHER_V1';
export const CALENDAR_CYCLE_STORAGE_KEY = 'ST_SMS_CALENDAR_CYCLES_V1';
export const CALENDAR_RECIPE_STORAGE_KEY = 'ST_SMS_CALENDAR_RECIPES_V1';
export const CALENDAR_OUTFIT_STORAGE_KEY = 'ST_SMS_CALENDAR_OUTFITS_V1';
export const TODAY_TREND_STORAGE_KEY = 'ST_SMS_TODAY_TREND_V1';
export const TODAY_TREND_FALLBACK_KEY = 'ST_SMS_TODAY_TREND_V1_LOCAL_FALLBACK';
export const TODAY_TREND_V2_STORAGE_KEY = 'ST_SMS_TODAY_TREND_V2';
export const TODAY_TREND_V2_FALLBACK_KEY = 'ST_SMS_TODAY_TREND_V2_LOCAL_FALLBACK';
export const TODAY_TREND_V2_AUTHORITY_KEY = 'ST_SMS_TODAY_TREND_V2_AUTHORITY_V1';
export const TODAY_TREND_V2_JOURNAL_PREFIX = 'ST_SMS_TODAY_TREND_V2_JOURNAL_V1:';
export const TODAY_TREND_INJECTION_KEY_PREFIX = 'ST_SMS_TODAY_TREND_INJECTION_V1:';
export const CHARACTER_BEHAVIOR_KEY = 'ST_SMS_CHARACTER_BEHAVIOR';
export const INJECTION_CONFIG_KEY = 'ST_SMS_INJECTION_CONFIG';
export const WORLD_BOOK_CONFIG_KEY = 'ST_SMS_WORLD_BOOK_CONFIG_V1';
export const GAL_BUBBLE_ENABLED_KEY = 'ST_SMS_GAL_BUBBLE_ENABLED';
export const VOICE_MAX_SEC = 60;
export const MODEL_VISIBLE_ROWS = 4;
export const MESSAGE_LENGTH_VALUES = Object.freeze(['persona', 'short', 'medium', 'long']);
export const FREQUENCY_VALUES = Object.freeze(['persona', 'never', 'rare', 'occasional', 'frequent']);
export const MAX_INJECTION_DEPTH = 10000;
export const EXTENSION_PROMPT_POSITIONS = Object.freeze({
    NONE: -1,
    IN_PROMPT: 0,
    IN_CHAT: 1,
    BEFORE_PROMPT: 2,
});
export const DEFAULT_GROUP_INJECTION = Object.freeze({
    position: EXTENSION_PROMPT_POSITIONS.IN_PROMPT,
    depth: 0,
    historyLimit: BIDIRECTIONAL_LIMIT,
});
export const PM_IDB_NAME = 'PhoneModeDB';
export const PM_IDB_STORE = 'kv';
export const IDB_MARKER = '__idb__';

export const POPOVER_SUPPORTED =
    typeof HTMLElement !== 'undefined' && HTMLElement.prototype.hasOwnProperty('popover');
